In [1]:
import numpy as np

y_predicted = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.30, 0.7, 1, 0, 0.5])

In [4]:
def mae_test(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted): #zip gives one value from each array in every iteration
        print(yt, yp)

In [5]:
mae_test(y_true, y_predicted)

0.3 1
0.7 1
1.0 0
0.0 0
0.5 1


In [8]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted): #zip gives one value from each array in every iteration
        total_error += abs(yt - yp)
    print("Total_error:", total_error)
    mae = total_error / len(y_true)
    print("MAE:", mae)
    return mae

In [9]:
mae(y_true, y_predicted)

Total_error: 2.5
MAE: 0.5


0.5

In [13]:
np.sum(np.abs(y_predicted - y_true)) #Short way with numpy

2.5

In [14]:
np.mean(np.abs(y_predicted - y_true)) #Short way with numpy

0.5

In [16]:
np.log([0.00000000000000000001])

array([-46.05170186])

We must change ones and zeros to numbers that are very close to them so that we don't get an error for log function. 

In [17]:
epsilon = 1e-15

In [18]:
y_predicted

array([1, 1, 0, 0, 1])

In [20]:
y_predicted_new = [max(i, epsilon) for i in y_predicted] #We are doing list comprehension in python here
y_predicted_new #We replaced zeros with epsilons

[1, 1, 1e-15, 1e-15, 1]

In [21]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new #We replaced ones with values that are closed to ones

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [22]:
y_predicted_new = np.array(y_predicted_new) #Converted to numpy array
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [23]:
np.log(y_predicted) #You will get an error

<ipython-input-23-d8d657355a01>:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [24]:
-np.mean(y_true*np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new)) #Log-loss function

17.2696280766844

In [27]:
#Now make all of this inside a function
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new) + (1 - y_true) * np.log(1 - y_predicted_new))    

In [28]:
log_loss(y_true, y_predicted)

17.2696280766844

In [29]:
#For MSE without numpy
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs((yt - yp)**2)
    print("Total_error:", total_error)
    mse = total_error / len(y_true)
    print("MSE:", mse)
    return mse

In [30]:
mse(y_true, y_predicted)

Total_error: 1.83
MSE: 0.366


0.366

In [39]:
np.sum(np.abs(y_predicted - y_true)**2)

1.83

In [40]:
np.mean(np.abs(y_predicted - y_true)**2)

0.366